dist: trusty
language: cpp
env:
    - COMPILER=g++-6                        # Helps the Travis to correctly show version
    - COMPILER=clang++-3.9                  # Helps the Travis to correctly show version
    - COMPILER=clang++-4.0                  # Helps the Travis to correctly show version

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9     # Whohoo!
            - llvm-toolchain-trusty-4.0     # Whohoo!
        packages:
            - g++-6
            - clang-3.9
            - clang-4.0


script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
    - cmake --build .
    - ./hello
