dist: trusty
language: cpp



matrix:
    include:
        - os: osx                           # Whohoo!
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode7.3
        - os: osx
          osx_image: xcode8.0
        - os: osx
          osx_image: xcode8.1
        - os: osx
          osx_image: xcode8.2

env:
    - COMPILER=g++-6
    - COMPILER=clang++-3.9
    - COMPILER=clang++-4.0

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9     # Whohoo!
            - llvm-toolchain-trusty-4.0     # Whohoo!
        packages:
            - g++-6
            - clang-3.9
            - clang-4.0


script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
    - cmake --build .
    - ./hello
