build: trusty
build_script:
    - mkdir build && cd build
    - cmake -G "%TOOLCHAIN_VERSION%" ..
    - cmake --build . --config %BUILD_TYPE%

test_script:
    - cmd: "%BUILD_TYPE%\\hello.exe"


environment:
    matrix:
        - TOOLCHAIN_VERSION: Visual Studio 14 Win64
          BUILD_TYPE: Release
        - TOOLCHAIN_VERSION: Visual Studio 14 Win64
          BUILD_TYPE: Debug
        - TOOLCHAIN_VERSION: MSYS Makefiles
          BUILD_TYPE: Release
